//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Applicants = new HashSet<Applicant>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Info { get; set; }
        public string Type { get; set; }
        public string Location { get; set; }
        public int User_id { get; set; }
    
        public virtual ICollection<Applicant> Applicants { get; set; }
        public virtual User User { get; set; }
    }
}
