//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.OrderHeads = new HashSet<OrderHead>();
        }
    
        public int Id { get; set; }
        public int productId { get; set; }
        public int count { get; set; }
        public int user_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderHead> OrderHeads { get; set; }
    }
}
